name: lint

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Rubocop Linter
      uses: andrewmcodes/rubocop-linter-action@latest
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
